name: Python Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.7

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda create -n tracepyci python=3.7 --yes
        conda activate tracepyci
        conda install --yes numpy scipy matplotlib scikit-learn pandas pytest pytest-cov
        pip install .

    - name: Run tests
      shell: bash -l {0}
      run: |
        conda activate tracepyci
        pytest tests/
